language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
    - DATABASE_URL="mysql://travis@127.0.0.1/dbdeploy"

before_script:
    - mysql -uroot -e "CREATE DATABASE dbdeploy" 
    - composer install

script: phpunit
